### ISSUE TITLE
Rename `Wallet` instances to `Account`

### ISSUE THREAD

**Issue by delaaxe** [eth-infinitism/bundler#11]
Even though this is not the `ethers.js` terminology, doing this rename is more consistent with the notion of Account Abstraction as in:
- Wallet: UI / client software that manages accounts
- Account: on-chain object that holds funds

**Comment by drortirosh** [comment]
Yes, I think that's a good idea ..

**Comment by yoavw** [comment]
I think so too.  Let's call the on-chain component Account.
