### ISSUE TITLE
Simulate validation does not enforce MIN_STAKE and MIN_UNSTAKE_DELAY configuration parameters

### ISSUE THREAD

**Issue by bshastry** [eth-infinitism/bundler#113]
The check for unstake delay in the reference bundler implementation

https://github.com/eth-infinitism/bundler/blob/a1cab449a45c991215648fe77b10148cc6466d62/packages/bundler/src/parseScannerResult.ts#L322C19-L323

only checks if unstake delay is greater than 1 second.

It should be rather

BigNumber.from(config.minunstakedelay).lt(entStakes.unstakeDelaySec)

Only the reputationmanager reads from config.minunstakedelay. The validationmanager (which handles simulatecall) is currently not passed this config parameter. May be one should?

https://github.com/eth-infinitism/bundler/blob/a1cab449a45c991215648fe77b10148cc6466d62/packages/bundler/src/modules/initServer.ts#L22

This explains why the bundler spec test passes even with a unstake delay of 2 seconds although it shouldn't

Similarly, the current enforcement of minimum stake value (specified in the minStake bundler configuration field) is missing. Currently, it suffices for stake to be greater than 1 wei

**Comment by drortirosh** [comment]
yes, the reference bundler doesn't use the configuration yet,and should be fixed.
