### ISSUE TITLE
Incorrect return parameter name from `HttpRpcClient.estimateUserOpGas` function on `@account-abstraction/sdk` node module

### ISSUE THREAD

**Issue by aviggiano** [eth-infinitism/bundler#131]
While trying to set up the whole infrastructure on my local environment (hardhat node, bundler, trampoline), it has come to my attention that `HttpRpcClient.estimateUserOpGas` return parameter name is incorrect on the `sdk` node module.

The node module exports `verificationGas` parameter, while the implementation uses [`verificationGasLimit`](https://github.com/eth-infinitism/bundler/blob/d935f2690f19c3e22d30da942479acac92cc3f29/packages/sdk/src/HttpRpcClient.ts#L55)

![screenshot-2023-08-06-12-20-53](https://github.com/eth-infinitism/bundler/assets/3029017/59505f15-cfda-40f1-9a99-62c46e8b1ef8)

This breaks trampoline, which uses [`verificationGas`](https://github.com/eth-infinitism/trampoline/blob/master/src/pages/Background/services/keyring.ts#L433). Since this value is never returned by the bundler, it is `undefined` and crashes the extension when passed onto `ethers.BigNumber.from`.

**Comment by aviggiano** [comment]
For those who may encounter this problem, this is an ugly quick fix:

```diff
diff --git a/src/pages/Background/services/keyring.ts b/src/pages/Background/services/keyring.ts
index 872c541..5175b7d 100644
--- a/src/pages/Background/services/keyring.ts
+++ b/src/pages/Background/services/keyring.ts
@@ -430,7 +430,7 @@ export default class KeyringService extends BaseService<Events> {
       gasParameters?.callGasLimit
     );
     const estimateVerificationGasLimit = ethers.BigNumber.from(
-      gasParameters?.verificationGas
+      (gasParameters as any).verificationGasLimit
     );
     const estimatePreVerificationGas = ethers.BigNumber.from(
       gasParameters?.preVerificationGas

```

**Comment by plusminushalf** [comment]
Hey thanks, fixed it in Trampoline. https://github.com/eth-infinitism/trampoline/commit/1477a96993cd548d31302cdd40b9bbc220154e37.

**Comment by aviggiano** [comment]
@plusminushalf Thanks, but will it compile?

I believe TypeScript will complain if we don't change the wrong SDK parameter definitions
