### ISSUE TITLE
Bundler considers EOA is an un-deployed SA

### ISSUE THREAD

**Issue by filmakarov** [eth-infinitism/bundler#137]
Recently, we have integrated eth-infinitism bundler into our Smart Account repo , so in our test cases we can send userOps to EP via bundler. 

When trying to send a deployment userOp (initcode not empty) via Bundler, I'm getting a `factory accesses un-deployed contract` error.
I believe this error is being thrown [here](https://github.com/eth-infinitism/bundler/blob/1d278b65e622aa8c6f1df0914260ea682b068e9a/packages/bundler/src/parseScannerResult.ts#L350).

After this error, it lists the addresses and the codesize. So I checked addresses and found out the address with 0 codesize is actually an EOA (signer created by the hardhat test env).

After a research, I realised, that the reason is the following:
`deployCounterFactualAccount` of factory calls `SmartAccount.init()` method which at some point calls the following code
```
assembly {
            size := extcodesize(owner)
}
```
It is the check, which is performed during setting the owner of Smart Account to make sure owner is not smart contract. As in this case Smart Account will be inaccessible since smart account will user `ecrecover`, not eip-1271 to validate the owner's signature.
We don't want to check if the expected signer is smart contract at the validation stage (and select ecrecover/isValidSignature accordingly) as it will add a gas overhead for _every_ userOp validation. We want to allow EOA's only instead by making only _one_ check at the initialization.

So, because of `extcodesize` opcode applied to EOA owner address, it is considered as smart contract by bundler. And since it's codesize is 0, the above error is thrown for an EOA, not an un-deployed smart contract.

Looking forward to hearing your thoughts on it.

**Comment by yoavw** [comment]
It doesn't matter whether it's an undeployed contract or an EOA (and there's no way to distinguish without verifying a signature).  Either way it violates rule 6 in the EIP:

`6. EXTCODEHASH, EXTCODELENGTH, EXTCODECOPY may not access address with no code.`

The reason for this rule is that it could be used for mass invalidation, much like a storage slot.  Any number of UserOps could check for an account with no code and revert if it has code.  And then a single CREATE can invalidate all of them.

**Comment by filmakarov** [comment]
Hey @yoavw, thank you for getting back!

Yes, I found rule 6 and understood why it was introduced. 
This rule is applicable not only to the validation stage but also to the deployment stage since un-paid mass invalidation can also happen at the deployment stage (and can cost even more), right?

> there's no way to distinguish without verifying a signature

can we safely suppose, that if at some point in the simulation, there is a call to 0x01 and it returns the address A, we can expect address A is not an un-deployed contract, but EOA, so we can allow `extcodelength` checks for it?

**Comment by yoavw** [comment]
> Yes, I found rule 6 and understood why it was introduced. This rule is applicable not only to the validation stage but also to the deployment stage since un-paid mass invalidation can also happen at the deployment stage (and can cost even more), right?

Yes, it's even more important in a deployment UserOp.  DoS that can happen during deployment has zero cost to the attacker since there's no need to even deploy accounts.

> can we safely suppose, that if at some point in the simulation, there is a call to 0x01 and it returns the address A, we can expect address A is not an un-deployed contract, but EOA, so we can allow `extcodelength` checks for it?

Technically yes (for now, but in the future we may have an opcode that sets code for an EOA to migrate it, and then it becomes unsafe).  However, why would it make sense to ecrecover a signature, and then also do an `extcodelength`?  If you already required the user to sign a message, and already spent the gas on ecrecover, then you already know what the result of the `extcodelength` will be.

**Comment by filmakarov** [comment]
> @filmakarov , not sure where you found the `deployCounterFactualAccount()` method. 

Yep, `deployCounterFactualAccount()` method is part of the [factory contract](https://github.com/bcnmy/scw-contracts/blob/a789f36dbdeaad2b68a9386a02bd0925fcd727e5/contracts/smart-account/factory/SmartAccountFactory.sol#L55) we developed. 

And the `extcodelength` check was [here](https://github.com/bcnmy/scw-contracts/blob/a789f36dbdeaad2b68a9386a02bd0925fcd727e5/contracts/smart-account/modules/EcdsaOwnershipRegistryModule.sol#L44-L50). Currently it is removed to be compliant to bundler restrictions. This method is called when the smart contract is deployed.

I agree that it should not be called "owner", I just put it like this for simplicity here.

**Comment by yoavw** [comment]
> However, for regular deployments (directly call `Factory.deployCounterFactualAccount()` via pre-AA txn) without this check, it will still be possible to set a smart contract as an owner (only authorized signer) instead of EOA thus making Smart Account inaccessible in the future.

Having another smart contract as a signer is problematic regardless of how it was set up.  During validation, this signer contract won't be able to access its own storage.  If it has non-immutable keys, it won't be able to access them from its `isValidSignature` (unless it was designed to be used solely as the signer of that particular account, and therefore stores its keys in a mapping keyed by the account).  And if it's a proxy, it won't even be able to access its implementation slot.

**Comment by filmakarov** [comment]
> Having another smart contract as a signer is problematic regardless of how it was set up. 

Yes, it is.  We recognized this when testing smart account signatures via bundler.
But the question is how do we ensure the user does not put a smart account address instead of EOA on initializing the Smart Account in case of directly calling `Factory.deployCounterFactualAccount()`.
At this point, I think that two measures can help:
1) Make deployment via userOp a default choice
2) Make off-chain verifications that the address provided is EOA

**Comment by yoavw** [comment]
Signers in an account are just signers, not accounts.  The fact that if the account uses ECDSA signatures the signers can also have associated Ethereum addresses is irrelevant to the protocol.

Regardless of the signature scheme used, the account validates its own deployment. The owner must provide a valid UserOp.signature for the UserOp that has initCode and deploys the account.  If it passes validation, you know the deployment was properly signed (according to the account's implementation).  If it doesn't, the account doesn't get deployed.

If you deploy an account outside the protocol, you lose this protection and you have to implement your own off-protocol safety check.
