### ISSUE TITLE
Cannot find module even with dependencies installed

### ISSUE THREAD

**Issue by rjborba** [eth-infinitism/bundler#14]
Hey guys, 
I'm trying to give the implementation a try but i'm facing an issue with the imports.

I ran yarn install, @account-abstraction/utils dependency appears on node_modules but I still get the error of Cannot find module. Any ideas?

**Comment by augustocollerone** [comment]
Hey guys, I'm having the same issue.

**Comment by fjun99** [comment]
this is a  workspace using `lerna`.

Run `yarn preprocess`.

**Comment by rjborba** [comment]
yarn preprocess output:

`lerna info Executing command in 3 packages: "yarn run tsc"
lerna ERR! yarn run tsc exited 2 in '@account-abstraction/utils'
lerna ERR! yarn run tsc stdout:
$ tsc
../../../../node_modules/@types/jest/index.d.ts(35,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'beforeEach' must be of type 'HookFunction', but here has type 'Lifecycle'.
../../../../node_modules/@types/jest/index.d.ts(37,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'afterEach' must be of type 'HookFunction', but here has type 'Lifecycle'.
../../../../node_modules/@types/jest/index.d.ts(38,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'describe' must be of type 'SuiteFunction', but here has type 'Describe'.
../../../../node_modules/@types/jest/index.d.ts(40,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'xdescribe' must be of type 'PendingSuiteFunction', but here has type 'Describe'.
../../../../node_modules/@types/jest/index.d.ts(41,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'it' must be of type 'TestFunction', but here has type 'It'.
../../../../node_modules/@types/jest/index.d.ts(43,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'xit' must be of type 'PendingTestFunction', but here has type 'It'.
../../../../node_modules/@types/jest/index.d.ts(44,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'test' must be of type 'TestFunction', but here has type 'It'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run tsc stderr:
error Command failed with exit code 2.
lerna ERR! yarn run tsc exited 2 in '@account-abstraction/utils'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by drortirosh** [comment]
if you could give a link to your repo, we might find the problem.

**Comment by rjborba** [comment]
@drortirosh I ended up not playing with that for a while, but I'm back trying to make it work. I'm using the up-to-date MAIN branch implement
