### ISSUE TITLE
Issue with Associative Storage Accessibility During Account Deployment

### ISSUE THREAD

**Issue by skimaharvey** [eth-infinitism/bundler#157]
I am encountering a discrepancy in the behavior of associative storage while adhering to the ERC-4337 standard, particularly when deploying an Account contract via `initCode` and subsequently executing a transaction.

Here's a breakdown of my setup:

- I have an owner contract that manages the reentrancy status of my Account contract.
- The reentrancy guard is defined as `mapping(address => bool) internal _reentrancyStatus` and is situated at slot 1 of my owner contract.
- The key for this mapping is the address of my Account contract.

I observed the following:

- When the Account contract is already deployed, the associative storage functions as expected.
- However, when deploying the Account contract through initCode first, followed by executing a transaction, I encounter an error: 
```
unstaked factory accessed 0x4e74b605bdaba2651fdd49d6751303a67e33b7c7 slot 0x9eb25a85dff830d4fc0f95d6af192b91783569f7c4eb4c68c5db9d950d5e061c".
``` 
Upon analyzing the error:

- The mentioned slot `0x9eb25a85dff830d4fc0f95d6af192b91783569f7c4eb4c68c5db9d950d5e061c` aligns with the expected value calculated with account `0x1375Ca41d29BA02f264bB9dcF66a6cbB8B9734B4` and a mapping situated at `slot 1` of the owner contract (`0x4e74b605bdaba2651fdd49d6751303a67e33b7c7`).
This raises a question:

- Is this behavior expected per the ERC-4337 standard? If so, why is associative storage accessible when the Account contract is deployed prior to the ERC-4337 transaction, but not when deployed via `initCode`?

I am keen to understand why there's a disparity in behavior and how to mitigate this issue. Any insights or clarification on the ERC-4337 standard concerning this scenario would be highly appreciated.

**Comment by skimaharvey** [comment]
Got this exact transaction to work using a stackup bundler 
https://explorer.execution.testnet.lukso.network/tx/0x71d7e44b1daf60a11acc3df3d1cb64102ec39894dda2ee8effb4da0eb9a88be4?tab=index

**Comment by drortirosh** [comment]
Accessing associated storage during account creation is allowed, but only if the factory is staked.
The reason for this restriction (and for that matter, for every other restriction) is that without it, it opens a door to a DoS attack on bundlers: In this case, just allowing a factory to access associated storage of account allows cheaply to create a large # of UserOps.
This scenario is indeed useful, we do allow it, as long as the factory is staked.

So your factory should call entryPoint.addStake, either from its constructor or using a helper method.
If the factory is ownable, you may also add unlockStake/withdrawStake methods, in case you ever want to "de-commission" an obsolete factory. Just make sure these methods are protected by "ownerOnly"

Note that you can't add a stake from another address: if the factory doesn't call addStake by itself, no other caller can add a stake on its behalf.

NOTE: Such attacks will become much more relevant as we add a public mempool shared by all bundlers, and we hope that by then more bundlers will fully enforce the rules.

**Comment by skimaharvey** [comment]
> Accessing associated storage during account creation is allowed, but only if the factory is staked. The reason for this restriction (and for that matter, for every other restriction) is that without it, it opens a door to a DoS attack on bundlers: In this case, just allowing a factory to access associated storage of account allows cheaply to create a large # of UserOps. This scenario is indeed useful, we do allow it, as long as the factory is staked.
> 
> So your factory should call entryPoint.addStake, either from its constructor or using a helper method. If the factory is ownable, you may also add unlockStake/withdrawStake methods, in case you ever want to "de-commission" an obsolete factory. Just make sure these methods are protected by "ownerOnly"
> 
> Note that you can't add a stake from another address: if the factory doesn't call addStake by itself, no other caller can add a stake on its behalf.
> 
> NOTE: Such attacks will become much more relevant as we add a public mempool shared by all bundlers, and we hope that by then more bundlers will fully enforce the rules.

Thank you for your answer.
My Factory is staked, what is not the owner of my account which is using associative storage. 
This transaction is working with a stackup bundler but not infinitism one

**Comment by drortirosh** [comment]
The owner itself doesn't have to stake, only UserOp entities (deployer, paymaster)

**Comment by skimaharvey** [comment]
@drortirosh any update on this? jsut following to see if the issue is coming from my factory logic (working with stackup) or if it is coming from infinitism bundler.

**Comment by drortirosh** [comment]
the error does say "unstaked factory accessed..." which means that staking the factory (deployer) should resolve the issue

**Comment by skimaharvey** [comment]
I tried again here is the full error 
```ts
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":43,\"error\":{\"message\":\"unstaked factory accessed 0x1336b113fa4e88ef6e934bd692bd4ce18d759407 slot 0xbf9473546016d90653f1650e63a3620d8a8e63cce57329daaa293dde4c144a5c\",\"data\":{\"factory\":\"0x5fac78f655d9023a0f1acc265564389f23c3e8c4\"},\"code\":-32502}}", error={"code":-32502,"data":{"factory":"0x5fac78f655d9023a0f1acc265564389f23c3e8c4"}}, requestBody="{\"method\":\"eth_sendUserOperation\",\"params\":[{\"sender\":\"0x6E08805eB7F16e3F6b79bEfc09c137941F0E510D\",\"nonce\":\"0x0000000012a6712f113536d8b01d99f72ce168c7e10901240000000000000000\",\"initCode\":\"0x5FaC78f655D9023a0F1acc265564389f23c3E8C4079c77620000000000000000000000005cd2f69c490bad0c7ad1be3c9899dfff833067550000000000000000000000001336b113fa4e88ef6e934bd692bd4ce18d75940700000000000000000000000012a6712f113536d8b01d99f72ce168c7e1090124000000000000000000000000fba87339e43d1b1ad0dcfe889a39489af753962c0ab5c7c3031ce60e4b2f0759300b95bbe9f92504fc3520db3ecb7044233623a8\",\"callData\":\"0x7f23690c5ef83ad9559033e6e941db7d7c495acdce616347d28e90c7ce47cbfcfcad3bc5000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000596f357c6a70546a2accab18748420b63c63b5af4cf710848ae83afc0c51dd8ad17fb5e8b3697066733a2f2f516d65637247656a555156587057347a53393438704e76636e51724a314b69416f4d36626466725663575a736e3500000000000000\",\"callGasLimit\":\"0x00000000000000000000000000000000000000000000000000000000000f4240\",\"verificationGasLimit\":\"0x00000000000000000000000000000000000000000000000000000000000aae60\",\"preVerificationGas\":\"0x00000000000000000000000000000000000000000000000000000000000249f0\",\"maxFeePerGas\":\"0x000000000000000000000000000000000000000000000000000000004190ab00\",\"maxPriorityFeePerGas\":\"0x000000000000000000000000000000000000000000000000000000004190ab00\",\"paymasterAndData\":\"0x\",\"signature\":\"0x73d3ecc752931b39d002381403affd65c0a358eb50ea324b50391e06fa4849555b7aae0d9246989614a75ababf685260bf48fdd97b3c0afae564623e6481dcef1c\"},\"0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789\"],\"id\":43,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://bundler-wp6f6rym5q-ez.a.run.app/rpc", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (/home/skima/code/lukso/lsp-smart-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/skima/code/lukso/lsp-smart-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at /home/skima/code/lukso/lsp-smart-contracts/node_modules/@ethersproject/web/src.ts/index.ts:341:28
    at step (/home/skima/code/lukso/lsp-smart-contracts/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/home/skima/code/lukso/lsp-smart-contracts/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/home/skima/code/lukso/lsp-smart-contracts/node_modules/@ethersproject/web/lib/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","id":43,"error":{"message":"unstaked factory accessed 0x1336b113fa4e88ef6e934bd692bd4ce18d759407 slot 0xbf9473546016d90653f1650e63a3620d8a8e63cce57329daaa293dde4c144a5c","data":{"factory":"0x5fac78f655d9023a0f1acc265564389f23c3e8c4"},"code":-32502}}',
  error: Error: unstaked factory accessed 0x1336b113fa4e88ef6e934bd692bd4ce18d759407 slot 0xbf9473546016d90653f1650e63a3620d8a8e63cce57329daaa293dde4c144a5c
      at getResult (/home/skima/code/lukso/lsp-smart-contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:142:28)
      at processJsonFunc (/home/skima/code/lukso/lsp-smart-contracts/node_modules/@ethersproject/web/src.ts/index.ts:383:22)
      at /home/skima/code/lukso/lsp-smart-contracts/node_modules/@ethersproject/web/src.ts/index.ts:320:42
      at step (/home/skima/code/lukso/lsp-smart-contracts/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/home/skima/code/lukso/lsp-smart-contracts/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/home/skima/code/lukso/lsp-smart-contracts/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: -32502,
    data: { factory: '0x5fac78f655d9023a0f1acc265564389f23c3e8c4' }
  },
  requestBody: '{"method":"eth_sendUserOperation","params":[{"sender":"0x6E08805eB7F16e3F6b79bEfc09c137941F0E510D","nonce":"0x0000000012a6712f113536d8b01d99f72ce168c7e10901240000000000000000","initCode":"0x5FaC78f655D9023a0F1acc265564389f23c3E8C4079c77620000000000000000000000005cd2f69c490bad0c7ad1be3c9899dfff833067550000000000000000000000001336b113fa4e88ef6e934bd692bd4ce18d75940700000000000000000000000012a6712f113536d8b01d99f72ce168c7e1090124000000000000000000000000fba87339e43d1b1ad0dcfe889a39489af753962c0ab5c7c3031ce60e4b2f0759300b95bbe9f92504fc3520db3ecb7044233623a8","callData":"0x7f23690c5ef83ad9559033e6e941db7d7c495acdce616347d28e90c7ce47cbfcfcad3bc5000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000596f357c6a70546a2accab18748420b63c63b5af4cf710848ae83afc0c51dd8ad17fb5e8b3697066733a2f2f516d65637247656a555156587057347a53393438704e76636e51724a314b69416f4d36626466725663575a736e3500000000000000","callGasLimit":"0x00000000000000000000000000000000000000000000000000000000000f4240","verificationGasLimit":"0x00000000000000000000000000000000000000000000000000000000000aae60","preVerificationGas":"0x00000000000000000000000000000000000000000000000000000000000249f0","maxFeePerGas":"0x000000000000000000000000000000000000000000000000000000004190ab00","maxPriorityFeePerGas":"0x000000000000000000000000000000000000000000000000000000004190ab00","paymasterAndData":"0x","signature":"0x73d3ecc752931b39d002381403affd65c0a358eb50ea324b50391e06fa4849555b7aae0d9246989614a75ababf685260bf48fdd97b3c0afae564623e6481dcef1c"},"0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"],"id":43,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://bundler-wp6f6rym5q-ez.a.run.app/rpc'
}
```

Here the factory is `0x5fac78f655d9023a0f1acc265564389f23c3e8c4`. You can verify that is has staked 2 LYX/ETH [here](https://explorer.execution.testnet.lukso.network/tx/0xca24800053e9e071186ac625e495e6cbd8a717eb3c028c9bf2c78550fe3293f2?tab=logs)

 [0x1336b113fa4e88ef6e934bd692bd4ce18d759407 ](https://explorer.execution.testnet.lukso.network/address/0x4e74b605bdaba2651fdd49d6751303a67e33b7c7?tab=contract) is not the factory but the owner of the Account.
 
Bundler is getting confused thinking it is the factory when it is actually the owner of the Account that uses associative storage. 

You can tell by looking at the error:
```ts
"error\":{\"message\":\"unstaked factory accessed 0x1336b113fa4e88ef6e934bd692bd4ce18d759407 slot 0xbf9473546016d90653f1650e63a3620d8a8e63cce57329daaa293dde4c144a5c\",\"data\":{\"factory\":\"0x5fac78f655d9023a0f1acc265564389f23c3e8c4\"}
```
It is giving out the correct factory `0x5fac78f655d9023a0f1acc265564389f23c3e8c4` but complaning that `0x1336b113fa4e88ef6e934bd692bd4ce18d759407 ` is an `unstaked factory accessed` which is not the case since it is not a factory but the owner of the account that is using the associative storage

**Comment by drortirosh** [comment]
the bundler is not confused, only the error message is misleading. The associative storage is accessed during the creation phase, and thus it is the factory that has to be staked.
The actual contract that performs the access doesn't really matter for staking, but we do report the contract that performed it.

I can't really understand why it fails, though. The debug traces are not enough, either. you can try to add a console.log inside "requireCondAndStake" for the content of "entStake" to understand why it things the factory is not staked.
