### ISSUE TITLE
Request: Release/Tag v0.6.1

### ISSUE THREAD

**Issue by nlordell** [eth-infinitism/bundler#159]
Would it be possible to create a v0.6.1 tag and/or release for https://github.com/eth-infinitism/bundler/commit/30dc20da10214415df60a5ee15a6bec0975c9af1?

It has some important fixes over v0.6.0 such as https://github.com/eth-infinitism/bundler/pull/127.

**Comment by drortirosh** [comment]
right.. pushed.
