### ISSUE TITLE
Tracing failed: fee cap less than block base fee: address 0x000000000000000000000000000000000000000 (Erigon?)

### ISSUE THREAD

**Issue by tomw1808** [eth-infinitism/bundler#167]
I was trying to get the bundler connected to hosted nodes which are apparently Erigon nodes. I am trying to run the bundler on the Polygon network.

The initial traceCall from `supportsDebugTraceCall` errors out and returns then false, leading to a wrongful error `FATAL: full validation requires a node with debug_traceCall. for local UNSAFE mode: use --unsafe`. Apparently the debug_traceCall endpoint is fine, it seems to me the message from Erigon is different than the message from geth if the gas price isn't set correctly.

I _think_ its connected to this one: https://github.com/ledgerwatch/erigon/issues/3494

The exact error coming back from the API is this one:

```
  at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"jsonrpc":"2.0","result":null,"error":{"message":"tracing failed: fee cap less than block base fee: address 0x0000000000000000000000000000000000000000, gasFeeCap: 0 baseFee: 31790422898","code":-32000},"id":45}',
    error: Error: tracing failed: fee cap less than block base fee: address 0x0000000000000000000000000000000000000000, gasFeeCap: 0 baseFee: 31790422898
        at getResult (/Users/thomas/Projects/Morpher/bundler/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:142:28)
        at processJsonFunc (/Users/thomas/Projects/Morpher/bundler/node_modules/@ethersproject/web/src.ts/index.ts:383:22)
        at /Users/thomas/Projects/Morpher/bundler/node_modules/@ethersproject/web/src.ts/index.ts:320:42
        at step (/Users/thomas/Projects/Morpher/bundler/node_modules/@ethersproject/web/lib/index.js:33:23)
        at Object.next (/Users/thomas/Projects/Morpher/bundler/node_modules/@ethersproject/web/lib/index.js:14:53)
        at fulfilled (/Users/thomas/Projects/Morpher/bundler/node_modules/@ethersproject/web/lib/index.js:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      code: -32000,
      data: undefined
    },
    requestBody: '{"method":"debug_traceCall","params":[{"from":"0x0000000000000000000000000000000000000000","to":"0x0000000000000000000000000000000000000000","data":"0x"},"latest",{"tracer"...
```

I am using chainnodes nodes for this one which offer a small free tier.

**Comment by drortirosh** [comment]
1. You can disable the call to "supportsDebugTraceCall" altogether, and see if the bundler does work.
2. different nodes implement the javascript tracer a bit differently (after all, its only spec is geth implementation..) , so it might require tweaking the tracer.
3. if you are able to execute a transaction through this bundler (e.g. by running "runop" in the bundler project), the please feel free to provide a PR to fix either the "supportsDebugTraceCall" and/or the actual tracer. Please provide it a long with a way to test (e.g. docker image and command-line to launch local erigon)
thanks.
