### ISSUE TITLE
Send ether from account wallet

### ISSUE THREAD

**Issue by sreeshmashaji** [eth-infinitism/bundler#168]
`const transaction = {
                      
                      to:"0x082364c4E413ea19855426e11c8B3D767104B91d",
                      value: amount,
                      gasLimit: 1e6,
                    };`

I want to send some fund from accountwallet to this 'to' account. But sendTransaction is not supported for accountwallet.
The how we send fund from accountwallet?

**Comment by drortirosh** [comment]
The SimpleWallet contract has `execute(target,balance,calldata)` method, which can send eth to another address.
to create a transaction from an account, you fill a "UserOperation", and in its callData, a call to execute.
You should use an SDK to create those UserOperation, though.
