### ISSUE TITLE
BunderHelper Contract - With revert in constructor

### ISSUE THREAD

**Issue by kanthgithub** [eth-infinitism/bundler#169]
## Question

https://github.com/eth-infinitism/bundler/blob/main/packages/bundler/contracts/BundlerHelper.sol#L9-L12

```
    constructor(IEntryPoint entryPoint, UserOperation[] memory userOps) {
        revert UserOpHashesResult(
            getUserOpHashes(entryPoint, userOps));
    }
```

this contract has revert in the constructor, where is this contract being used if not needed can this be removed?
Please correct me if i missed any.

**Comment by blewater** [comment]
This constructor employs a 'Constructor Revert' pattern to calculate user operation hashes off-chain, saving on gas costs. Its use is more contextual and can be traced by searching for [`GetUserOpHashes`](https://github.com/search?q=repo%3Aeth-infinitism/bundler%20GetUserOpHashes&type=code)."

**Comment by drortirosh** [comment]
yes. a contract with revert in the constructor is a pattern for "solidity script". it is never deployed on chain. running the constructor call with "eth_call" will return the revert data, thus executing the "script" and returning the value.
in this case, it is a single RPC call to get the hashes of multiple contracts
