### ISSUE TITLE
Suggestion: separating  sdk from SimpleWallet implementation

### ISSUE THREAD

**Issue by fjun99** [eth-infinitism/bundler#17]
Try to use the `ERC4337EthersProvider` and `ERC4337EthersSigner` in the sdk. And I have a suggestion for the sdk.

Currently, they are intertwingled with the SimpleWallet implementation.

- `SimpleWallet` contract & `SimpleWalletDeployer`
- `SimpleWalletAPI`
- `wrapProvider()` in `Provider.ts`

As for a showcase, it is ok. 

But as a developer who is trying to use this SDK, I would like to:

- write my wallet contract: `MyWalletContract`, `MyWalletDeployer`
- implement my wallet API extending `BaseWalletAPI`:  ` MyWalletAPI`
- my own wrapProvider which uses my own `MyWalletAPI`

I have tried this and it can work. Code snippets of `mywrapProvider`:

```ts
export async function mywrapProvider (
    originalProvider: JsonRpcProvider,
    config: ClientConfig,
    originalSigner: Signer = originalProvider.getSigner(),
    walletFacotryAddress: string,
    walletIndex: number = 0
  ): Promise<ERC4337EthersProvider> {

    const entryPoint = EntryPoint__factory.connect(config.entryPointAddress, originalProvider)

    const smartWalletAPI: BaseWalletAPI = new MySimpleWalletAPI({
      provider: originalProvider,
      entryPointAddress: config.entryPointAddress,
      owner: originalSigner,
      factoryAddress: walletFacotryAddress,
      paymasterAPI: config.paymasterAPI,
      index: walletIndex,
      walletAddress:config.walletAddres
    })
...
}
```

So maybe we can separate sdk from SimpleWallet implementation so that developers can import sdk and use it directly. Thanks for consideration.

**Comment by drortirosh** [comment]
Sorry for the late response. we don't look much into github for messages, but mostly on discord.
As for your question: SimpleWallet (and SimpleWalletAPI) was built as a sample. it is implemented purely above the "BaseXX" base element, which are intended to be used by developers, as you demonstrate, so you can have a completely implementation without referencing the "sample" ones, neither in solidity nor in the javascript wrapper.
