### ISSUE TITLE
too high verificationgaslimit

### ISSUE THREAD

**Issue by kl456123** [eth-infinitism/bundler#172]
userop with too high verificationgaslimit  can make bundler to resend reverted tx all the times until all gas of operator used up. we need to check it when creating bundle to prevent it.

**Comment by drortirosh** [comment]
bundlers should have a limit on verificationGasLimit for various reasons.
Bundlers should not accept UserOps with verificationGasLimit too high. actual number need to be established, but it is probably below 200k gas (enough for creating a multisig account proxy, such as Safe)
