### ISSUE TITLE
stop with one hour

### ISSUE THREAD

**Issue by heyb130** [eth-infinitism/bundler#177]
I used the main code branch, which was successfully deployed on the server, but when using nohub and running in the background, it automatically stopped running within an hour. What is the reason for this?

**Comment by drortirosh** [comment]
not sure what "nouhb" means.
You might try to run it with logs enabled (e.g. `DEBUG=aa*`) and check.
That said, the reference implementation is not a production-grade server. It is a fully functional bundler to show how to implement the various validation rules required defined in ERC-4337 and ERC-7562/
