### ISSUE TITLE
Bundler fails to start

### ISSUE THREAD

**Issue by TSKHot** [eth-infinitism/bundler#183]
Environment: Windows 10, cygwin 3.5.0-1.x86_64, yarn version v1.22.19, npm version 9.6.4, node version 20.11.0

Issue 1:

Running 'yarn && yarn preprocess' failed with the following:

	src/ValidationManager.ts(297,17): error TS2365: Operator '>=' cannot be applied to types 'BigNumberish' and 'number'

so cast 'calcPreVerificationGas1' as BigNumberish on line 297 of ValidationManager.ts

Issue 2:

Ran up Geth using 'geth --http --http.api personal,eth,net,web3,debug --dev --dev.period 13 --rpc.allow-unprotected-txs --allow-insecure-unlock'

Deployed an Entrypoint contract through our own tool and updated the bundler.config.json file with the address.

Calling 'yarn run bundler'  fails with the following:

command-line arguments:  { config: './localconfig/bundler.config.json', auto: false }
Merged configuration: {"port":"3000","entryPoint":"0x9decd0823a4d84fac1f400c316781cb5b047d95c","unsafe":false,"conditionalRpc":false,"minStake":
"1","minUnstakeDelay":0,"gasFactor":"1","network":"http://127.0.0.1:8545","beneficiary":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","minBalance
":"1","mnemonic":"./localconfig/mnemonic.txt","maxBundleGas":9000000000,"autoBundleInterval":3,"autoBundleMempoolSize":10}
url= http://127.0.0.1:8545
== debugrpc was undefined
Aborted: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":56,\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * p
rice + value: balance 0, tx cost 10000000000000000, overshot 10000000000000000\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sen
dRawTransaction\",\"params\":[\"0xf8a58085174876e800830186a08080b853604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf31ba022222222222222222222222222222222222222222222222222
22222222222222a02222222222222222222222222222222222222222222222222222222222222222\"],\"id\":56,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="
http://127.0.0.1:8545", code=SERVER_ERROR, version=web/5.7.1)
error Command failed with exit code 1.

Geth console shows the following:

INFO [02-27|16:17:24.569] Submitted transaction                    hash=0xbbd5610f4fe8dfa4f358ff401aec669fc061ba0e6dcc287611e248384bbc64d5 from=0x7b32ac604407bF0BA97a74d86e2461633472Ae83 nonce=1 recipient=0x3fAB184622Dc19b6109349B94811493BF2a45362 value=10,000,000,000,000,000
WARN [02-27|16:17:24.583] Served eth_sendRawTransaction            conn=127.0.0.1:51622 reqid=56 duration="545.2µs" err="insufficient funds for gas * price + value: balance 0, tx cost 10000000000000000, overshot 10000000000000000"

0x7b32ac604407bF0BA97a74d86e2461633472Ae83 is the developer account and has all the funds. Through our own tool we can successfully carry out the transfer to 0x3fAB184622Dc19b6109349B94811493BF2a45362

Why is this a problem for the Bundler submitted transaction?

**Comment by drortirosh** [comment]
it works fine on mac and linux, so there isn't something can do. sorry.

**Comment by TSKHot** [comment]
Hey Dror. 
Thanks for responding. Our systems are all .net based and primarily developed on Windows. We're working on a couple of web3 projects and recently started to incorporate Account Abstraction.
I understand you've got a lot of stuff going on and developing for and testing in all environments isn't a priority, However, if we want to get buy-in for Web3 from, basically, the rest of the world, it might be worth throwing some resources at ensuring the development community behind the most prolific systems (MS) are well supported.
Anyway, we got the Stackup Bundler working in private mode, so we're able to push on.
Cheers.
