### ISSUE TITLE
Method rundler_maxPriorityFeePerGas is not supported

### ISSUE THREAD

**Issue by sdelvalle57** [eth-infinitism/bundler#190]
Trying to get userop maxPriorityFeePerGas using:

```
    const rundlerMaxPriorityFeePerGas = await apiClient.post("/rpc", {
          jsonrpc: "2.0",
          method: "rundler_maxPriorityFeePerGas",
          params: [],
        });
        if (rundlerMaxPriorityFeePerGas.status !== 200) {
          throw new Error(
            `Failed: ${JSON.stringify(
              rundlerMaxPriorityFeePerGas.data.error.message
            )}`
          );
        }
```

But Im getting `rundler_maxPriorityFeePerGas error: {"message":"Method rundler_maxPriorityFeePerGas is not supported","code":-32601} RpcError: Method rundler_maxPriorityFeePerGas is not supported` error

Is there another way to fetch this value?

**Comment by drortirosh** [comment]
seems like an issue in the "rundler". I suggest you open it against their repo, not the reference implementation bundler
