### ISSUE TITLE
full validation requires a node with debug_traceCall.

### ISSUE THREAD

**Issue by phamhongphuc1999** [eth-infinitism/bundler#193]
running bundler [v6](https://github.com/eth-infinitism/bundler/tree/releases/0.6.0) in BSC Mainnet or BSC Testnet by trying some rpcs, I always caused an error: `full validation requires a node with debug_traceCall. for local UNSAFE mode: use --unsafe`. 
However, my problem is that if I use the flag unsafe, it works but when I send a user operation transaction from my app, I usually get some unknown errors????.
How can I resolve this problem and what full validation requires a node is????. I want a sufficient testnet to test my app, can you list for me some sufficient networks???

**Comment by drortirosh** [comment]
The "unsafe" mode should be fully functional - that is, it doesn't affect handling of valid UserOperations.
it is called "unsafe" because there are possible denial of service attacks on the bundler itself - namely, UserOperations that get included, but later become invalid and cause on-chain reverts.
Without knowing the errors you got (or the UserOperation you submitted) we can resolve the issue.

**Comment by phamhongphuc1999** [comment]
> The "unsafe" mode should be fully functional - that is, it doesn't affect handling of valid UserOperations. it is called "unsafe" because there are possible denial of service attacks on the bundler itself - namely, UserOperations that get included, but later become invalid and cause on-chain reverts. Without knowing the errors you got (or the UserOperation you submitted) we can resolve the issue.

Thank you for your response, I realize that my problem doesn't relate to "unsafe" flag, maybe I run an incorrect calldata.

**Comment by luongs3** [comment]
@phamhongphuc1999 how did you resolve the problem? I got the same one.

**Comment by phamhongphuc1999** [comment]
> @phamhongphuc1999 how did you resolve the problem? I got the same one.

@luongs3  it's a bug, it's just a warning. You can follow one of two ways:
- Using a fully supported debug_traceCall provider.
- just adding flat --unsafe when you run. For example, instead of npm run dev, you should run npm run dev --unsafe.
