### ISSUE TITLE
no formatting rules provided

### ISSUE THREAD

**Issue by hexcowboy** [eth-infinitism/bundler#26]
when working on any packages downstream, i often format the file so long lines can automatically wrap. however, there don't appear to be any prettier rules in this repository and when i format a file, the whole file changes.

this makes it difficult when working downstream because when merging from upstream, there are lots of conflicts.

it would be nice if this repository could provide a .prettierrc or similar, and format all existing code to make downstream development easier.

**Comment by drortirosh** [comment]
can you please provide a PR to add it? thanks.
