### ISSUE TITLE
Facing Revert Error on geth logs

### ISSUE THREAD

**Issue by satya-netobjex** [eth-infinitism/bundler#84]
getting execution reverted error on geth console when trying to run test `yarn run runop --deployFactory --network localhost`  

steps to reproduce this error : 
`
1. docker run --rm -ti --name geth -p 8545:8545 ethereum/client-go:v1.10.26 \
  --miner.gaslimit 12000000 \
  --http --http.api personal,eth,net,web3,debug \
  --http.vhosts '*,localhost,host.docker.internal' --http.addr "0.0.0.0" \
  --ignore-legacy-receipts --allow-insecure-unlock --rpc.allow-unprotected-txs \
  --dev \
  --verbosity 2 \
  --nodiscover --maxpeers 0 --mine --miner.threads 1 \
  --networkid 1337
2. yarn && yarn preprocess
3.yarn hardhat-deploy --network localhost
4.yarn run bundler
5.yarn run runop --deployFactory --network http://localhost:8545/ --entryPoint 0x0576a174d229e3cfa37253523e645a78a0c91b57`

attaching logs of geth,bundler and test console for your reference
![Screenshot from 2023-03-28 17-12-21](https://user-images.githubusercontent.com/111412540/228234457-d3040de6-11bc-4fd4-80c8-fa555da06925.png)
![Screenshot from 2023-03-28 17-09-56](https://user-images.githubusercontent.com/111412540/228234475-9026ae4e-5c3d-4fe0-a9d3-92d621a6860b.png)
![Screenshot from 2023-03-28 17-09-46](https://user-images.githubusercontent.com/111412540/228234481-b0e07881-4e21-4172-9d07-decdce3acfef.png)

**Comment by drortirosh** [comment]
getting reverts on geth console is normal...
we use simulation functions. These must not be called on real network. So they always revert, and return whatever return values they need in the revert data. 
It works find, but geth log shows these as errors.

**Comment by luongs3** [comment]
@drortirosh what do you mean "must not be called on real network". 
In the code base, We use simulation result to make op, send to op pool. So I assume that I really need to to simulation.

**Comment by luongs3** [comment]
@satya-netobjex did you resolve this?
