### ISSUE TITLE
Runop seems does not make a deposit to the entrypoint

### ISSUE THREAD

**Issue by brew0722** [eth-infinitism/bundler#87]
(+latest updated)
https://github.com/eth-infinitism/bundler/issues/87#issuecomment-1512349142

for an issue readers,
I made an error in my estimation of the issue and stand corrected.

UserOp users do not need to explicitly call deposit.
When the Entrypoint handles the UserOp, it will try to make the deposit directly from the user's balance as the prefund is insufficient.
https://github.com/eth-infinitism/account-abstraction/blob/9b5f2e4bb30a81aa30761749d9e2e43fee64c768/contracts/core/EntryPoint.sol#L408

However, the reason you're still getting an AA21 error in runop.ts is because of an asynchronization issue with sendTransaction.
By waiting for balance funding as follows, the problem no longer occurs.
`const fundTx = await signer.sendTransaction({ to: addr, value: requiredBalance.sub(bal) }) await fundTx.wait()`

-----
I ran the following simple test procedure from the readme.

> Usage:
> run yarn && yarn preprocess
> deploy contracts with yarn hardhat-deploy --network localhost
> run yarn run bundler (or yarn run bundler --unsafe, if working with "hardhat node")
> Now your bundler is active on local url http://localhost:3000/rpc
> 
> To run a simple test, do yarn run runop --deployFactory --network http://localhost:8545/ --entryPoint 0x0576a174d229e3cfa37253523e645a78a0c91b57

However, I ran into an `AA21` error in the process. because that the AA user did not prefund.
So I checked the code of `runop` task, it seems that it only initializes the balance of the CA, and is missing the staking to the `entrypoint`.
https://github.com/eth-infinitism/bundler/blob/ef0751cdcf8e865c2550435c3046a6a0b54ef52c/packages/bundler/src/runner/runop.ts#L176

```
  const bal = await getBalance(addr)
  console.log('account address', addr, 'deployed=', await isDeployed(addr), 'bal=', formatEther(bal))
  // TODO: actual required val
  const requiredBalance = parseEther('0.1')
  if (bal.lt(requiredBalance.div(2))) {
    console.log('funding account to', requiredBalance)
    await signer.sendTransaction({
      to: addr,
      value: requiredBalance.sub(bal)
    })
  } else {
    console.log('not funding account. balance is enough')
  }

  const dest = addr
  const data = keccak256(Buffer.from('nonce()')).slice(0, 10)
  console.log('data=', data)
  await client.runUserOp(dest, data)
```

I replaced it with a W/A code that does a `depositTo` instead of sendTransaction above, like this, and I was able to run the `UserOp` normally.
`await (await entrypoint.depositTo(addr, {value: requiredBalance})).wait()`

Looking at the implementation of `simpleAccount`, it looks like it will only be a deposit if explicitly use `addDeposit`, could you please review?

**Comment by emailtovamos** [comment]
Could you post your changed code so that I can test? Since I am also getting the same error. Thanks!

**Comment by brew0722** [comment]
> Could you post your changed code so that I can test? Since I am also getting the same error. Thanks!

Just replace the code with the following
```
    console.log('funding account to', requiredBalance)
    await signer.sendTransaction({
      to: addr,
      value: requiredBalance.sub(bal)
    })
```
->
```
    console.log('funding account to', requiredBalance)
    await (await entrypoint.depositTo(addr, {value: requiredBalance.sub(bal)})).wait()
```

**Comment by emailtovamos** [comment]
@brew0722 Thanks. 

How do you get the `entrypoint` in this case?

I added the following:
```
const entryPoint = EntryPoint__factory.connect(ENTRY_POINT, provider)
await (await entryPoint.depositTo(addr, {value: requiredBalance.sub(bal)})).wait()
```

But getting this error:
```
reason: 'sending a transaction requires a signer',
code: 'UNSUPPORTED_OPERATION',
operation: 'sendTransaction'
```

**Comment by brew0722** [comment]
@emailtovamos 
The error looks like the provider doesn't have a signer set.
This seems to be an ethers configuration issue unrelated to AA.

**Comment by brew0722** [comment]
for an issue readers,
I made an error in my estimation of the issue and stand corrected.

UserOp users do not need to explicitly call depositTo.
When the Entrypoint handles the UserOp, it will try to make the deposit directly from the user's balance as the prefund is insufficient.
https://github.com/eth-infinitism/account-abstraction/blob/9b5f2e4bb30a81aa30761749d9e2e43fee64c768/contracts/core/EntryPoint.sol#L408

However, the reason you're still getting an AA21 error in runop.ts is because of an asynchronization issue with sendTransaction.
By waiting for balance funding as follows, the problem no longer occurs.
`
    const fundTx = await signer.sendTransaction({
      to: addr,
      value: requiredBalance.sub(bal)
    })
    await fundTx.wait()
`
