### ISSUE TITLE
Minor miscalculation of minimum amount of ops to be included while calculating status.

### ISSUE THREAD

**Issue by tinchoabbate** [eth-infinitism/bundler#94]
Hey folks, I was just reading the code of the bundler's `ReputationManager` module, and noticed what seems to be a small oversight.

In the [`getStatus` function](https://github.com/eth-infinitism/bundler/blob/ef0751cdcf8e865c2550435c3046a6a0b54ef52c/packages/bundler/src/modules/ReputationManager.ts#L128), the code appears to be miscalculating the minimum amount of ops to be included ([stored](https://github.com/eth-infinitism/bundler/blob/ef0751cdcf8e865c2550435c3046a6a0b54ef52c/packages/bundler/src/modules/ReputationManager.ts#L139) in `minExpectedIncluded` local var).

According [to the spec](https://github.com/eth-infinitism/account-abstraction/blob/develop/eip/EIPS/eip-4337.md#specification-2) it must be:
```
min_expected_included = opsSeen[paymaster] // MIN_INCLUSION_RATE_DENOMINATOR
```

which as far as I my newbie typescript goes, should translate to:

```typescript
const minExpectedIncluded = Math.floor(entry.opsSeen / this.params.minInclusionDenominator)
```

But [the code is now doing](https://github.com/eth-infinitism/bundler/blob/ef0751cdcf8e865c2550435c3046a6a0b54ef52c/packages/bundler/src/modules/ReputationManager.ts#L139):

```typescript
const minExpectedIncluded = Math.min(entry.opsSeen / this.params.minInclusionDenominator)
```

Hope I'm following this correctly. I'm not that familiar with the bundler's codebase yet.

**Comment by drortirosh** [comment]
You're absolutely correct... How about making a PR to fix it ?
